apiVersion: argoproj.io/v1alpha1
kind: Experiment
metadata:
  name: example-experiment
spec:
  progressDeadlineSeconds: 30
  templates:
  - name: canary
    replicas: 1
    selector:
      matchLabels:
        app: guestbook-ui
    template:
      metadata:
        labels:
          app: guestbook-ui
      spec:
        containers:
        - name: guestbook-ui
          image: hashicorp/http-echo:latest
          args:
            - "-text='hello world'"
          imagePullPolicy: Always
          ports:
          - name: http
            containerPort: 8080
            protocol: TCP
