apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: guestbook-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: busybox:stable-uclibc
        name: guestbook-ui
        ports:
        - containerPort: 80
  strategy:
    canary:
      steps:
      - analysis:
          templates:
          - templateName: http-benchmark
