apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: guestbook-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: hashicorp/http-echo:latest
        args:
          - "-text='hello world'"
        name: guestbook-ui
        ports:
        - containerPort: 80
  strategy:
    canary:
      canaryService: guestbook-ui-canary
      steps:
      - experiment:
          templates:
          - name: example-experiment
            specRef: example-experiment
          analyses:
          - name : http-benchmark
            templateName: http-benchmark
            args:
            - name: host
              value: guestbook-ui-canary
