apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: guestbook-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.1
        name: guestbook-ui
        ports:
        - containerPort: 80
  strategy:
    canary:
      steps:
      - experiment:
          duration: 30m
          templates:
          - name: canary-experiment
            specRef: example-experiment
            selector:
              matchLabels:
                app: guestbook-ui
            metadata:
              labels:
                app: guestbook-ui
          analyses:
          - name: load-test
            templateName: http-benchmark
            args:
            - name: host
              value: guestbook-ui
