apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: guestbook-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.1
        name: guestbook-ui
        ports:
        - containerPort: 80
  strategy:
    canary:
      steps:
        - experiment:
          duration: 60s
          templates:
          - name: preview
            # specRef is a convenience reference indicating that the canary's pod spec should be used in this experiment.
            specRef: canary
            # The preview template's selector/labels are overwritten so that they are different
            # than the rollout's selector, allowing it to be reached separately
            selector:
              matchLabels:
                app: preview
            metadata:
              labels:
                app: preview
          # The 'load-test' AnalysisTemplate uses `wrk` to perform benchmarking. See: load-test-analysis.yaml
          analyses:
          - name: load-test
            templateName: http-benchmark
            args:
            - name: host
              value: preview-testing
      # canaryService: guestbook-ui-canary
      # stableService: guestbook-ui
      # canaryMetadata:
      #   annotations:
      #     role: canary
      #   labels:
      #     role: canary
      # stableMetadata:
      #   annotations:
      #     role: stable
      #   labels:
      #     role: stable
      # steps:
      # - setCanaryScale:
      #     replicas: 1
      # - pause: {duration: 1m}
      # - analysis:
      #     templates:
      #       - templateName: webmetrics
      # trafficRouting:
      #   istio:
      #     virtualService:
      #       name: rollout-vsvc  # required
      #       routes:
      #         - primary
