# This analysis template demonstrates the use of the job metric provider.
# It runs wrk (https://github.com/wg/wrk), an HTTP benchmarking tool, against the supplied hostname
# and then interprets the error rate for success or failure
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: http-benchmark
spec:
  metrics:
  - name: http-benchmark
    failureLimit: 3
    interval: 5s
    count: 20
    provider:
      job:
        spec:
          template:
            spec:
              containers:
              - name: http-benchmark
                image: argoproj/load-tester:latest
                command: [sh, -xec]
                args:
                - |
                  sleep 5; exit 0
              restartPolicy: Never
          backoffLimit: 0